<#
.Synopsis
    Generate content for README.md with synopses of PS functions

.Outputs
    Markdown
#>
[CmdletBinding()]
param(
[string] $Folder = $PWD,
[string[]] $FolderExcludes,
[switch] $Recurse,
[string] $GroupPrefix,
[string[]] $Groups
)

Push-Location $Folder

try {

    "# Command Synopses`n"

    $progressActivity = "Generating Help"

    function doModule
    {
    [CmdletBinding()]
    param( $moduleName )
        Write-Progress -Activity $progressActivity -CurrentOperation $moduleName
        $module = Import-Module $moduleName -PassThru -Force
        @"
## $($module.Name) Module Functions

``````PowerShell
Import-Module $moduleName
``````

"@
        $commands = Get-Command -Module $module
        $commandsGroups = $commands | Select-Object @{n='c';e={$_}},@{n='t';e={ $_.name -cmatch "-$GroupPrefix([A-Z][a-z]+)" ? ($matches[1] -in $Groups ? $matches[1] : "Misc"): "Misc" }} | Group-Object t

        $commandsGroups | ForEach-Object {
            if ($commandsGroups.Count -gt 1) {
                "`n## $($_.name) Functions`n"
            }
            @"
Command     | Synopsis
------------|---------|
"@
            $_.Group.c | ForEach-Object {
                $help = Get-help $_ | Where-Object ModuleName -eq $module
                $desc = "";
                if ( $help -and $help.synopsis )
                {
                $desc = $help.synopsis.trim()
                }
                "$($_.name) | $desc"
            }
        }
        Remove-Module $module
    }

    function doLooseFiles( $folderName )
    {
        $files = Get-ChildItem *-*.ps1
        if ( -not $files )
        {
            return
        }
@"
    ## Files in $folderName
    ``````PowerShell
    Set-Location $PWD
    ``````
    Command     | Synopsis
    ------------|---------|
"@

        Get-ChildItem *-*.ps1 | ForEach-Object {
            $help = Get-help $_
            ".\$(Split-Path $_.Name -Leaf) | $($help.synopsis.trim())"
        }
    }

    function doFolder( $folder, $Recurse )
    {
    Push-Location $folder
    Write-Progress -Activity $progressActivity -Status $folder

    $module = Get-Item *.psd1
    if (!$module) {
        $module = Get-Item *.psm1
    }
    if ( $module )
    {
        Write-Progress -Activity $progressActivity -Status "$folder - $module"
        $module | ForEach-Object { doModule $_ }
    }
    else
    {
        doLooseFiles $folder
        if ( $Recurse )
        {
            Get-ChildItem -Directory | Where-Object name -notin $FolderExcludes | ForEach-Object {
            doFolder $_ $Recurse
            }
        }
    }
    Pop-Location
    }

    if ( "." -notin $FolderExcludes )
    {
        doFolder $PWD $Recurse
    }
    else
    {
        Get-ChildItem -Directory | Where-Object name -notin $FolderExcludes | ForEach-Object {
            doFolder $_ $Recurse
        }
    }

    Write-Progress $progressActivity -Completed
    "`nGenerated by New-HelpOutput.ps1 on $(Get-Date)"
}
finally {
    Pop-Location
}